{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helm2-basic.serviceAccountName" . }}
  labels:
{{ include "helm2-basic.labels" . | indent 4 }}
{{- end -}}
