harnessApiVersion: '1.0'
type: OTHER
commandUnitType: COMMAND
commandUnits:
- command: ./shn_deploy.py -t configure  2>&1
  commandUnitType: EXEC
  deploymentType: SSH
  name: Configure
  scriptType: BASH
  workingDirectory: ${WINGS_RUNTIME_PATH}
targetToAllEnv: true
