apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}
data:
  hello: world
---

kind: "DeploymentConfig"
apiVersion: apps.openshift.io/v1
metadata:
  name: {{.Values.name}}
spec:
  template: 
    metadata:
      labels:
        name: {{.Values.name}}
    spec:
      containers:
      - name: nginx
        image: twalter/openshift-nginx:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{.Values.name}}
  replicas: 1
  selector:
    name: {{.Values.name}}
  triggers:
    - type: "ConfigChange" 
  strategy: 
    type: "Rolling"
