apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}
data:
  sudipto: test

kind: "DeploymentConfig"
apiVersion: apps.openshift.io/v1
metadata:
  name: {{.Values.name}}
spec:
  template: 
    metadata:
      labels:
        name: {{.Values.name}}
    spec:
      containers:
      - name: nginx
        image: twalter/openshift-nginx:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{.Values.name}}
replicas: 5 
  selector:
    name: {{.Values.name}}
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "helloworld"
        from:
          kind: "ImageStreamTag"
          name: "origin-ruby-sample:latest"
  strategy: 
    type: "Rolling"
        rollingParams:
      pre:
        failurePolicy: Abort
        execNewPod:
          containerName: helloworld 
          command: [ "/usr/bin/command", "arg1", "arg2" ] 
        env:
          config:
              key1: value1
            secrets:
              key2: value2
          volumes:
            - data 
    type: "Recreate"
resources:
  limits:
    cpu: "100m" 
    memory: "256Mi" 