harnessApiVersion: '1.0'
type: OTHER
commandUnitType: COMMAND
commandUnits:
- command: "#!/bin/bash -ex\n[ ! -e ./shn_deploy.py ] || ./shn_deploy.py -t unconfigure "
  commandUnitType: EXEC
  deploymentType: SSH
  name: Unconfigure
  scriptType: BASH
  workingDirectory: ${WINGS_RUNTIME_PATH}
- command: "#!/bin/bash -ex\n[ ! -e ./shn_deploy.py ] || ./shn_deploy.py -t unconfigure "
  commandUnitType: EXEC
  deploymentType: SSH
  name: Unconfigure
  scriptType: BASH
  workingDirectory: ${WINGS_RUNTIME_PATH}
targetToAllEnv: true
