harnessApiVersion: '1.0'
type: BUILD
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - OGP2bnvASa-D8oua0YdmhQ
phases:
- daemonSet: false
  name: Phase 1
  phaseSteps:
  - type: PREPARE_STEPS
    name: Prepare Steps
    steps:
    - type: SERVICENOW_CREATE_UPDATE
      name: ServiceNow
      properties:
        DESCRIPTION: aa
        IMPACT: '1'
        SHORT_DESCRIPTION: aa
        URGENCY: '1'
        publishAsVar: true
        serviceNowAction: CREATE_TICKET
        serviceNowCreateUpdateParams:
          action: CREATE
          snowConnectorId: Z7JVd2s2RFeHuj6FOTxZzA
          ticketType: INCIDENT
          fields:
            URGENCY: '1'
            IMPACT: '1'
            DESCRIPTION: aa
            SHORT_DESCRIPTION: aa
          additionalFields: null
        snowConnectorId: Z7JVd2s2RFeHuj6FOTxZzA
        sweepingOutputName: snow
        sweepingOutputScope: WORKFLOW
        ticketType: INCIDENT
    - type: APPROVAL
      name: Approval
      properties:
        approvalStateParams:
          serviceNowApprovalParams:
            snowConnectorId: Z7JVd2s2RFeHuj6FOTxZzA
            ticketType: INCIDENT
            issueNumber: ${snow.issueNumber}
            approvalField: status
            approvalOperator: equalsTo
            approvalValue: New
        approvalStateType: SERVICENOW
        publishAsVar: true
        sweepingOutputName: appVar
        sweepingOutputScope: WORKFLOW
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeoutMillis: 600000
        variables: null
    stepsInParallel: false
  - type: COLLECT_ARTIFACT
    name: Collect Artifact
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    steps:
    - type: SHELL_SCRIPT
      name: Shell Script
      properties:
        commandPath: null
        connectionAttributes: null
        executeOnDelegate: true
        host: null
        outputVars: ''
        publishAsVar: false
        scriptString: echo "${appVar}"
        scriptType: BASH
        sshKeyRef: null
        sweepingOutputName: null
        sweepingOutputScope: null
        tags: ''
        templateVariables: ''
        timeoutMillis: 60000
    stepsInParallel: false
  provisionNodes: false
  statefulSet: false
templatized: false
