harnessApiVersion: '1.0'
type: OTHER
commandUnitType: COMMAND
commandUnits:
- command: |
    [ ! -e ./shn_bin/configure.py ] || ./shn_bin/configure.py
  commandUnitType: EXEC
  deploymentType: SSH
  name: Configure
  scriptType: BASH
  workingDirectory: ${WINGS_RUNTIME_PATH}
targetToAllEnv: true
